// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: { redirect_uri?: string }) => {
      // OAuth functionality removed
      return {
        error: new Error("OAuth functionality has been disabled"),
      };
    },
  },
};
